### ISSUE TITLE
Set minimum word length

### ISSUE THREAD

**Issue by jessamp** [ytiurin/hyphen#14]
Is there a way to set the minimum word length to hyphenate? I'm trying to make my app as accessible as possible and supporting large text mode. I have some very short words that are supposed to fit in small spaces. I was hoping to still hyphenate small words so there wouldn't be any awkward trailing characters.

**Comment by krisztianb** [comment]
Could you give an example? I am not sure that I completely understand.

As a side note: I noticed that hyphen does not hyphenate words that are shorter than 5 characters if you use the German dictionary. But that is probably due to the matching patterns in the dictionary file. I looked at how MS Word does it and it behaves the same.

For example: You have the word "eine" which could be hyphenated as "ei-" and "ne". But it's not hyphenated by Word nor by hyphen. If you look at the German grammar and hyphenation rules, you will see that there are very specific rules and exceptions as to which words shorter than 5 letters are allowed to by hyphenated and which not.

**Comment by jessamp** [comment]
I was originally thinking of forcing a hyphenation with some words. For example, "lea-ve". However, I think I'll just use the standard pattern provided and not hyphenate certain words. 

However, I have a separate question. How come in the string "language & location" a soft hyphen is added to "language" but not "location"?

**Comment by krisztianb** [comment]
Well, that seems to be a bug then. Did you try hyphenating the words one by one? Does that make a difference? In our application I use hyphen only for the words that are located at the "edge" of a line.

**Comment by jessamp** [comment]
For some reason, I don't see your last comment here on the thread....

But to answer your question, when I process the words individually they both get hyphenated. It's just when the whole string is hyphenated that only "language" is hyphenated. Since our application is supporting large font mode, we're hyphenating everything; not just edge cases.

**Comment by krisztianb** [comment]
You don't see my comment, because I decided to delete it and instead try your example for myself. :-)

This is my test page using the latest version 1.1.1 of hy-phen:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Test hy-phen</title>
  </head>

<body>

<script src="./en-gb.js"></script>
<script src="./hyphen.js"></script>

<script type="text/javascript">
  let hyphenateEnGb = createHyphenator(hyphenationPatternsEnGb, {debug: false, hyphenChar:'-'});

  let input = "language & location";
  let output = hyphenateEnGb(input);

  console.log(output);
</script>

</body></html>
```

The output I get in the console is:

> lan-guage & loc-a-tion

Which is correct. Are you using the latest version? Try to create a minimal simple example on your side (like mine above) and see if the error is still there.

**Comment by Wiejeben** [comment]
If anyone finds themselves in the same scenario:

```js
/**
 * Hyphenate words with a minimum given length.
 *
 * @param {string} subject
 * @param {number} minWordLength
 * @return {string}
 */
hyphenate(subject, minWordLength = 20) {
    if (typeof subject !== 'string') {
        return '';
    }

    const words = subject.split(' ');

    return words.map(word => {
        if (word.length < minWordLength) {
            return word;
        }

        return hyphenateSync(word);
    }).join(' ');
}
```

**Comment by ytiurin** [comment]
Hi @Wiejeben , sorry for the late response.

For now, the minimum word length intended for hyphenation is 5 charachters long.
Accoding to your script, the minimum word length should be 20 characters.
As I understand, you want to hyphenate only very long words, is that correct?

If so, I can add an additional option to the constructor to cover your usecase. But keep in mind, that the minimum possible value of that option will still be 5 chars to sustain reasonable performance of the lib execution itself.

**Comment by Wiejeben** [comment]
@ytiurin Having an option inside the library would be pretty useful, keeping default at 5 would obviously be no problem.

**Comment by ytiurin** [comment]
@jessamp @Wiejeben @krisztianb 

I added an option `minWordLength` in version 1.6.0, hope this is useful :)

Thank you guys for your time and contribution!
