### ISSUE TITLE
repeated patterns inside a word

### ISSUE THREAD

**Issue by jaumeortola** [ytiurin/hyphen#17]
There is an obvious problem when a word contains a repeated pattern (e.g. blablabla, nanana, papapa). The pattern is used only once [here](https://github.com/ytiurin/hyphen/blob/master/hyphen.js#L40), but it should be used in every occurrence of the pattern.

**Comment by krisztianb** [comment]
I am not sure if this is a bug as those are not real life words. It might be that the patterns are only designed for real words of a given language. But I don't understand the pattern matching technique fully, so I might be wrong here.

I've tried tinkering around with the code so that every match of a pattern is recognized, but this does not give the desired result either, which should be:

    bla-bla-bla
    na-na-na
    pa-pa-pa

**Comment by jaumeortola** [comment]
I found the problem in real Catalan words: nenes, papa, mama, baba, banana, patata... 
These changes fix the problem: https://github.com/ytiurin/hyphen/pull/18

**Comment by krisztianb** [comment]
Thank you. I tested your changes and they do fix some similar errors with German hyphenation I am using.

I commented on your code in the PR. Please have a look.

**Comment by jaumeortola** [comment]
I can't see any comment on the code.

**Comment by krisztianb** [comment]
Sorry. I looks like I forgot to click "Submit review". I've never done a code review here on GitHub before.

**Comment by ytiurin** [comment]
Solved with https://github.com/ytiurin/hyphen/pull/18 PR
